# Generated by Django 4.2.1 on 2023-12-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='media/default_profile.jpg', upload_to='media')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
