# Generated by Django 4.2.1 on 2024-01-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='quota',
            field=models.CharField(choices=[('50', '50 MB'), ('500', '500 MB'), ('1000', '1000 MB')], default=50, max_length=6),
        ),
    ]
