# Generated by Django 4.2.1 on 2023-12-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_file', '0004_uploadfile_created_at_alter_uploadfile_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='description',
            field=models.TextField(blank=True, default='no description'),
        ),
    ]
