# Generated by Django 4.2.1 on 2024-01-24 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_file', '0006_alter_uploadfile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
