# Generated by Django 4.2.1 on 2024-01-03 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_file', '0006_alter_uploadfile_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilepermission',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_permissions', to='user_file.uploadfile'),
        ),
        migrations.AlterField(
            model_name='uploadfilepermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='uploadfilepermission',
            unique_together={('file', 'user')},
        ),
    ]
